# fly.toml app configuration file generated for subwayyy on 2024-07-09T11:28:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[[statics]]
guest_path = "/static"  
url_prefix = "/"

app = 'subwayyy'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = "80"

[[services.ports]]
  handlers = ["tls", "http"]
  port = "443"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
