[tool.poetry]
name = "mj-demo"
version = "0.1.0"
description = ""
authors = ["mjlee <mjlee@vaiv.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
gunicorn = "^22.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
